package evolutionYoutube;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Listas_fijas_reproduccion_ventana extends VerticalLayout {
	protected VerticalLayout historial;
	protected HorizontalLayout miniatura;
	protected Label titulo;
	protected VerticalLayout editar4;
	protected Button editar;
	protected VerticalLayout megusta;
	protected HorizontalLayout miniatura2;
	protected Label titulo1;
	protected VerticalLayout editar3;
	protected Button editar2;

	public Listas_fijas_reproduccion_ventana() {
		Design.read(this);
	}
}
