package evolutionYoutube;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_perfil_usuario_ventana extends CssLayout {
	protected HorizontalLayout avatar;
	protected Label apodo;
	protected Label visitas;
	protected Label numerosuscriptores;
	protected NativeButton volver;
	protected NativeButton suscribirse;
	protected HorizontalLayout videossubidos;
	protected HorizontalLayout listas_reproduccion;
	protected VerticalLayout suscripciones;
	protected HorizontalLayout listas_reproduccion1;
	protected VerticalLayout seguidores;

	public Ver_perfil_usuario_ventana() {
		Design.read(this);
	}
}
