package evolutionYoutube;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Video_subido_propietario_ventana extends CssLayout {
	protected VerticalLayout video;
	protected VerticalLayout miniatura;
	protected Image uno;
	protected Label reproducciones;
	protected Image dos;
	protected Label megusta;
	protected Button editarminiatura;
	protected TextField url;
	protected Label tres;
	protected Label cuatro;
	protected Label titulo;
	protected Label cinco;
	protected Label descripcion;
	protected Label seis;
	protected Label categorias;
	protected Label siete;
	protected Label etiquetas;
	protected Button modificar;
	protected Button eliminar;
	protected Button vervideo;

	public Video_subido_propietario_ventana() {
		Design.read(this);
	}
}
